import { z } from "zod";

// Shared wire format between self-hosted Campux instances (reporter in
// apps/server) and the central telemetry collector (apps/dash, served at
// dash.campux.top). Bump TELEMETRY_SCHEMA_VERSION when the payload shape
// changes incompatibly; the collector keeps accepting older versions it knows.
//
// Privacy contract: the report must stay anonymous and aggregate-only. No user
// identifiers, QQ numbers, hostnames, tenant names/slugs, or post content may
// ever be added here. The only identity is a random UUID generated by the
// instance, plus an optional operator-provided display label.
export const TELEMETRY_SCHEMA_VERSION = 1;

// Abuse hardening: the collector is an open endpoint on the internet, so every
// field is bounded. Counts are capped far above any plausible real value;
// payloads exceeding the caps are rejected rather than clamped.
const count = z.number().int().min(0).max(1_000_000_000);
const shortString = (max: number) => z.string().min(1).max(max);

export const telemetryRuntimeSchema = z.object({
  bunVersion: shortString(32),
  platform: shortString(32),
  arch: shortString(32),
  inDocker: z.boolean(),
});

export const telemetryCountsSchema = z.object({
  tenants: count,
  users: count,
  memberships: count,
  postsTotal: count,
  postsLast24h: count,
  botsEnabled: count,
  publishTargets: count,
  privateMessagesReceived: count,
  adminRepliesSent: count,
});

export const telemetryFeaturesSchema = z.object({
  emailConfigured: z.boolean(),
  aiTenants: count,
});

export const telemetryReportSchema = z.object({
  schemaVersion: z.literal(TELEMETRY_SCHEMA_VERSION),
  instanceId: z.string().uuid(),
  // Opt-in, operator-provided label (CAMPUX_TELEMETRY_INSTANCE_NAME). Absent by
  // default so instances stay anonymous unless the operator chooses otherwise.
  instanceName: shortString(64).optional(),
  reportedAt: z.string().datetime({ offset: true }),
  version: shortString(64),
  environment: z.enum(["development", "test", "production"]),
  deployMode: z.enum(["single", "multi"]),
  setupCompleted: z.boolean(),
  uptimeSeconds: z.number().min(0).max(10 * 365 * 24 * 60 * 60),
  runtime: telemetryRuntimeSchema,
  counts: telemetryCountsSchema,
  features: telemetryFeaturesSchema,
});

export type TelemetryReport = z.infer<typeof telemetryReportSchema>;

export type TelemetryParseResult = { ok: true; report: TelemetryReport } | { ok: false; error: string };

// Strict-but-forward-compatible parse: unknown keys are stripped (a newer
// instance reporting extra fields is still accepted), known keys are validated
// hard so garbage never reaches storage.
export function parseTelemetryReport(input: unknown): TelemetryParseResult {
  const result = telemetryReportSchema.safeParse(input);
  if (!result.success) {
    const first = result.error.issues[0];
    return { ok: false, error: first ? `${first.path.join(".") || "payload"}: ${first.message}` : "invalid payload" };
  }
  return { ok: true, report: result.data };
}
