export const builtInSvgAvatarFilenames = [
  "2026马.svg",
  "彩色骷髅头.svg",
  "橙色余晖.svg",
  "戴眼镜的小鸟.svg",
  "豆包.svg",
  "乖巧的猫.svg",
  "互联网职业男.svg",
  "开心.svg",
  "可爱的猫.svg",
  "可爱熊猫.svg",
  "头像-男学生1.svg",
  "头像-男学生2.svg",
  "头像-男学生3.svg",
  "头像-男学生4.svg",
  "头像-男学生5.svg",
  "头像-男学生6.svg",
  "头像-女学生1.svg",
  "头像-女学生2.svg",
  "头像-女学生3.svg",
  "头像-女学生4.svg",
  "头像-女学生5.svg",
  "头像-女学生6.svg",
  "兔兔真可爱.svg",
  "小狗.svg",
  "熊猫吃惊.svg",
  "粽子过端午.svg",
] as const;
